### ISSUE TITLE
Update YouTube's APK to 17.26.35

### ISSUE THREAD

**Issue by JulienRevest** [xemulat/MyFilesForDDL#3]
The provided YouTube APK for the stable build of ReVanced Packer is outdated, and most of the patches do not work on the version hosted on this repo.
An updated APK would solve the issue and provide working builds.

Such an APK can be found [here for example](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-26-35-release/youtube-17-26-35-android-apk-download/).

**Comment by xemulat** [comment]
okey
